USE Roca_Maya;

-- TABLA: TBL_MS_ROLES (Según documento)
CREATE TABLE TBL_MS_ROLES (
    ID_ROL INT AUTO_INCREMENT PRIMARY KEY,
    ROL VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(255),
    -- Campos de auditoría según documento
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREACION VARCHAR(50),
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_MODIFICACION VARCHAR(50)
);

-- TABLA: TBL_MS_USUARIO (Según documento) - MEJORADA CON 2FA
CREATE TABLE TBL_MS_USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(50) NOT NULL UNIQUE,
    NOMBRE_USUARIO VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'NUEVO' CHECK (ESTADO IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO', 'NUEVO')),
    CONTRASENA VARCHAR(255) NOT NULL,
    ID_ROL INT NOT NULL,
    FECHA_ULTIMA_CONEXION DATETIME,
    FECHA_VENCIMIENTO DATE,
    CORREO_ELECTRONICO VARCHAR(100),
    INTENTOS_FALLIDOS INT DEFAULT 0,
    -- Campos adicionales para funcionalidades extendidas
    GOOGLE_ID VARCHAR(100) UNIQUE,
    TWO_FACTOR_ENABLED BOOLEAN DEFAULT FALSE,
    TWO_FACTOR_SECRET VARCHAR(100),
    -- MEJORAS DE 2FA RECOMENDADAS
    SECRET_2FA VARCHAR(255) NULL,
    ACTIVO_2FA TINYINT(1) DEFAULT 0 NOT NULL,
    FECHA_ACTIVACION_2FA DATETIME NULL,
    ULTIMO_CODIGO_2FA VARCHAR(10) NULL,
    INTENTOS_2FA_FALLIDOS INT DEFAULT 0,
    BLOQUEO_2FA_HASTA DATETIME NULL,
    -- Campos de auditoría según documento
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREACION VARCHAR(50),
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_MODIFICACION VARCHAR(50),
    FOREIGN KEY (ID_ROL) REFERENCES TBL_MS_ROLES(ID_ROL),
    INDEX idx_usuario_estado (ESTADO),
    INDEX idx_usuario_fecha_vencimiento (FECHA_VENCIMIENTO),
    INDEX idx_usuario_2fa (ACTIVO_2FA)
);

-- TABLA: TBL_MS_HIST_CONTRASEÑA (Según documento)
CREATE TABLE TBL_MS_HIST_CONTRASEÑA (
    ID_HIST INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50),
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_MODIFICACION VARCHAR(50),
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_MS_USUARIO(ID_USUARIO) ON DELETE CASCADE,
    INDEX idx_hist_usuario (ID_USUARIO)
);

-- TABLA: TBL_MS_PARAMETROS (Según documento)
CREATE TABLE TBL_MS_PARAMETROS (
    ID_PARAMETRO INT AUTO_INCREMENT PRIMARY KEY,
    PARAMETRO VARCHAR(100) NOT NULL UNIQUE,
    VALOR VARCHAR(255) NOT NULL,
    DESCRIPCION VARCHAR(500),
    -- Campos de auditoría
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREACION VARCHAR(50),
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_MODIFICACION VARCHAR(50)
);

-- TABLA: TBL_OBJETOS (Según documento)
CREATE TABLE TBL_OBJETOS (
    ID_OBJETO INT AUTO_INCREMENT PRIMARY KEY,
    OBJETO VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(255),
    TIPO_OBJETO VARCHAR(50),
    -- Campos de auditoría
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREACION VARCHAR(50),
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_MODIFICACION VARCHAR(50)
);

-- TABLA: TBL_PERMISOS (Según documento)
CREATE TABLE TBL_PERMISOS (
    ID_PERMISO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ROL INT NOT NULL,
    ID_OBJETO INT NOT NULL,
    PERMISO_INSERCION BOOLEAN DEFAULT FALSE,
    PERMISO_ELIMINACION BOOLEAN DEFAULT FALSE,
    PERMISO_ACTUALIZACION BOOLEAN DEFAULT FALSE,
    PERMISO_CONSULTA BOOLEAN DEFAULT FALSE,
    -- Campos de auditoría
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREACION VARCHAR(50),
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_MODIFICACION VARCHAR(50),
    FOREIGN KEY (ID_ROL) REFERENCES TBL_MS_ROLES(ID_ROL),
    FOREIGN KEY (ID_OBJETO) REFERENCES TBL_OBJETOS(ID_OBJETO),
    UNIQUE KEY unique_rol_objeto (ID_ROL, ID_OBJETO)
);

-- ============================================
-- MÓDULO MÉDICO (TABLAS MÉDICAS)
-- ============================================

-- TABLA: TBL_PACIENTE
CREATE TABLE TBL_PACIENTE (
    ID_PACIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE,
    GENERO ENUM('MASCULINO','FEMENINO','OTRO'),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20),
    CORREO_ELECTRONICO VARCHAR(100),
    TIPO_DOCUMENTO_IDENTIDAD ENUM('DNI','PASAPORTE','LICENCIA','OTRO') DEFAULT 'DNI',
    NUMERO_DOCUMENTO_IDENTIDAD VARCHAR(50) UNIQUE,
    RTN_PACIENTE VARCHAR(50),
    ESTADO_CIVIL ENUM('SOLTERO','CASADO','DIVORCIADO','VIUDO','UNION_LIBRE'),
    OCUPACION VARCHAR(100),
    NOMBRE_CONTACTO_EMERGENCIA VARCHAR(200),
    TELEFONO_CONTACTO_EMERGENCIA VARCHAR(20),
    PARENTESCO_CONTACTO_EMERGENCIA VARCHAR(50),
    ESTADO ENUM('ACTIVO','INACTIVO','BLOQUEADO') DEFAULT 'ACTIVO',
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO_REGISTRO INT,
    FECHA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50),
    USUARIO_MODIFICACION VARCHAR(50),
    FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES TBL_MS_USUARIO(ID_USUARIO),
    INDEX idx_paciente_documento (NUMERO_DOCUMENTO_IDENTIDAD),
    INDEX idx_paciente_nombres (NOMBRES, APELLIDOS),
    INDEX idx_paciente_estado (ESTADO)
);

-- TABLA: TBL_ESPECIALIDADES
CREATE TABLE TBL_ESPECIALIDADES (
    ID_ESPECIALIDAD INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_ESPECIALIDAD VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION TEXT,
    COLOR_HEXADECIMAL VARCHAR(7) DEFAULT '#3498DB',
    ICONO VARCHAR(50),
    ESTADO ENUM('ACTIVA','INACTIVA') DEFAULT 'ACTIVA',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50),
    USUARIO_MODIFICACION VARCHAR(50)
);

-- TABLA: TBL_DOCTOR_ESPECIALIDAD
CREATE TABLE TBL_DOCTOR_ESPECIALIDAD (
    ID_DOCTOR_ESPECIALIDAD INT AUTO_INCREMENT PRIMARY KEY,
    ID_DOCTOR INT NOT NULL,
    ID_ESPECIALIDAD INT NOT NULL,
    FECHA_ASIGNACION DATE DEFAULT (CURRENT_DATE()),
    ESTADO ENUM('ACTIVA','INACTIVA') DEFAULT 'ACTIVA',
    ES_PRIMARIA BOOLEAN DEFAULT FALSE,
    ANIOS_EXPERIENCIA INT DEFAULT 0,
    -- Campos de auditoría
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREACION VARCHAR(50),
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_MODIFICACION VARCHAR(50),
    FOREIGN KEY (ID_DOCTOR) REFERENCES TBL_MS_USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES TBL_ESPECIALIDADES(ID_ESPECIALIDAD) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_TBL_DOCTOR_ESPECIALIDAD (ID_DOCTOR, ID_ESPECIALIDAD),
    INDEX idx_doctor_especialidad_estado (ESTADO)
);

-- TABLA: TBL_CITAS
CREATE TABLE IF NOT EXISTS TBL_CITAS (
    ID_CITA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PACIENTE INT NOT NULL,
    ID_DOCTOR INT NOT NULL,
    FECHA_CITA DATETIME NOT NULL,
    FECHA_FIN_ESTIMADA DATETIME,
    DURACION_ESTIMADA_MIN INT DEFAULT 30,
    ESTADO ENUM('PROGRAMADA','CONFIRMADA','PRECLINICA','CONSULTA_MEDICA','FINALIZADA','CANCELADA','NO_ASISTIO') DEFAULT 'PROGRAMADA',
    MOTIVO_CONSULTA TEXT,
    ID_USUARIOCREADOR INT NOT NULL,
    
    -- CAMPOS DE AUDITORÍA COMPLETOS Y CORREGIDOS
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREACION VARCHAR(50),
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_MODIFICACION VARCHAR(50),
    
    OBSERVACIONES TEXT,
    PRIORIDAD ENUM('NORMAL','URGENTE','ALTA') DEFAULT 'NORMAL',
    TIPO_CITA ENUM('PRIMERA_VEZ','CONTROL','EMERGENCIA','PROCEDIMIENTO') DEFAULT 'PRIMERA_VEZ',
    CANAL_REGISTRO ENUM('PRESENCIAL','TELEFONO','WEB','MOVIL','API') DEFAULT 'PRESENCIAL',
    
    -- Llaves foráneas
    FOREIGN KEY (ID_PACIENTE) REFERENCES TBL_PACIENTE(ID_PACIENTE),
    FOREIGN KEY (ID_DOCTOR) REFERENCES TBL_MS_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_USUARIOCREADOR) REFERENCES TBL_MS_USUARIO(ID_USUARIO),
    
    -- Índices para optimización
    INDEX idx_citas_paciente (ID_PACIENTE),
    INDEX idx_citas_doctor (ID_DOCTOR),
    INDEX idx_citas_estado (ESTADO),
    INDEX idx_citas_fecha (FECHA_CITA),
    INDEX idx_citas_creacion (FECHA_CREACION),
    INDEX idx_citas_modificacion (FECHA_MODIFICACION)
);

-- TABLA: TBL_HISTORIAL_MEDICO
CREATE TABLE TBL_HISTORIAL_MEDICO (
    ID_HISTORIAL INT AUTO_INCREMENT PRIMARY KEY,
    ID_PACIENTE INT NOT NULL UNIQUE,
    ALERGIAS JSON,
    ENFERMEDADES_CRONICAS JSON,
    CIRUGIAS_PREVIAS JSON,
    MEDICAMENTOS_ACTUALES JSON,
    ANTECEDENTES_FAMILIARES JSON,
    HABITOS JSON COMMENT 'TABACO, ALCOHOL, EJERCICIO, ETC.',
    VACUNAS JSON,
    NOTAS_IMPORTANTES TEXT,
    FECHA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ID_USUARIO_ACTUALIZO INT,
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50),
    USUARIO_MODIFICACION VARCHAR(50),
    FOREIGN KEY (ID_PACIENTE) REFERENCES TBL_PACIENTE(ID_PACIENTE) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO_ACTUALIZO) REFERENCES TBL_MS_USUARIO(ID_USUARIO)
);

-- TABLA: TBL_PRECLINICA
CREATE TABLE TBL_PRECLINICA (
    ID_PRECLINICA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CITA INT NOT NULL UNIQUE,
    ID_USUARIO_ENFERMERIA INT NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    TEMPERATURA DECIMAL(4,2),
    PRESION_SISTOLICA INT,
    PRESION_DIASTOLICA INT,
    FRECUENCIA_CARDIACA INT,
    FRECUENCIA_RESPIRATORIA INT,
    SATURACION_OXIGENO DECIMAL(5,2),
    PESO DECIMAL(5,2),
    TALLA DECIMAL(5,2),
    IMC DECIMAL(4,2) GENERATED ALWAYS AS (PESO / (TALLA * TALLA)) STORED,
    GLUCOSA DECIMAL(5,2),
    PERIMETRO_ABDOMINAL DECIMAL(5,2),
    OBSERVACIONES TEXT,
    ESTADO_GENERAL ENUM('BUENO','REGULAR','MALO') DEFAULT 'BUENO',
    SIGNOS_VITALES_JSON JSON,
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50),
    USUARIO_MODIFICACION VARCHAR(50),
    FOREIGN KEY (ID_CITA) REFERENCES TBL_CITAS(ID_CITA) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO_ENFERMERIA) REFERENCES TBL_MS_USUARIO(ID_USUARIO),
    INDEX idx_preclinica_cita (ID_CITA)
);

-- TABLA: TBL_CONSULTA_MEDICA
CREATE TABLE TBL_CONSULTA_MEDICA (
    ID_CONSULTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CITA INT NOT NULL UNIQUE,
    ID_PACIENTE INT NOT NULL,
    ID_DOCTOR INT NOT NULL,
    MOTIVO_CONSULTA TEXT,
    SINTOMAS JSON,
    EXAMEN_FISICO JSON,
    DIAGNOSTICO_PRINCIPAL TEXT,
    CODIGO_CIE10_PRINCIPAL VARCHAR(10),
    DIAGNOSTICO_SECUNDARIO TEXT,
    CODIGO_CIE10_SECUNDARIO VARCHAR(10),
    TRATAMIENTO TEXT,
    RECOMENDACIONES TEXT,
    OBSERVACIONES TEXT,
    FECHA_CONSULTA DATETIME DEFAULT CURRENT_TIMESTAMP,
    PROXIMA_CITA_RECOMENDADA DATE,
    TIPO_CONSULTA ENUM('GENERAL','ESPECIALIDAD','CONTROL','EMERGENCIA') DEFAULT 'GENERAL',
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50),
    USUARIO_MODIFICACION VARCHAR(50),
    FOREIGN KEY (ID_CITA) REFERENCES TBL_CITAS(ID_CITA) ON DELETE CASCADE,
    FOREIGN KEY (ID_PACIENTE) REFERENCES TBL_PACIENTE(ID_PACIENTE),
    FOREIGN KEY (ID_DOCTOR) REFERENCES TBL_MS_USUARIO(ID_USUARIO),
    INDEX idx_consulta_cita (ID_CITA),
    INDEX idx_consulta_paciente (ID_PACIENTE),
    INDEX idx_consulta_fecha (FECHA_CONSULTA)
);

-- ============================================
-- MÓDULO DE MEDICAMENTOS Y FARMACIA
-- ============================================

-- TABLA: TBL_INVENTARIO_MEDICAMENTO
CREATE TABLE TBL_INVENTARIO_MEDICAMENTO (
    ID_MEDICAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_MEDICAMENTO VARCHAR(255) NOT NULL,
    NOMBRE_GENERICO VARCHAR(255),
    DESCRIPCION TEXT,
    PRESENTACION VARCHAR(100),
    CONCENTRACION VARCHAR(50),
    VIA_ADMINISTRACION VARCHAR(50),
    STOCK_ACTUAL INT DEFAULT 0,
    STOCK_MINIMO INT DEFAULT 10,
    STOCK_MAXIMO INT DEFAULT 100,
    PRECIO_COMPRA DECIMAL(10,2),
    PRECIO_VENTA DECIMAL(10,2),
    LOTE VARCHAR(100),
    FECHA_VENCIMIENTO DATE,
    PROVEEDOR VARCHAR(255),
    REQUIERE_RECETA BOOLEAN DEFAULT TRUE,
    ESTADO ENUM('ACTIVO','INACTIVO','VENCIDO') DEFAULT 'ACTIVO',
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO_REGISTRO INT,
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50),
    USUARIO_MODIFICACION VARCHAR(50),
    FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES TBL_MS_USUARIO(ID_USUARIO),
    INDEX idx_medicamento_nombre (NOMBRE_MEDICAMENTO),
    INDEX idx_medicamento_vencimiento (FECHA_VENCIMIENTO),
    INDEX idx_medicamento_stock (STOCK_ACTUAL)
);

-- TABLA: TBL_PRESCRIPCION
CREATE TABLE TBL_PRESCRIPCION (
    ID_PRESCRIPCION INT AUTO_INCREMENT PRIMARY KEY,
    ID_CONSULTA INT NOT NULL,
    ID_MEDICAMENTO INT NOT NULL,
    FECHA_PRESCRIPCION DATETIME DEFAULT CURRENT_TIMESTAMP,
    DOSIS VARCHAR(50) NOT NULL,
    FRECUENCIA VARCHAR(50),
    DURACION VARCHAR(50),
    CANTIDAD_TOTAL INT,
    INSTRUCCIONES_ADICIONALES TEXT,
    ESTADO ENUM('ACTIVA','COMPLETADA','SUSPENDIDA') DEFAULT 'ACTIVA',
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50),
    USUARIO_MODIFICACION VARCHAR(50),
    FOREIGN KEY (ID_CONSULTA) REFERENCES TBL_CONSULTA_MEDICA(ID_CONSULTA) ON DELETE CASCADE,
    FOREIGN KEY (ID_MEDICAMENTO) REFERENCES TBL_INVENTARIO_MEDICAMENTO(ID_MEDICAMENTO),
    INDEX idx_prescripcion_consulta (ID_CONSULTA)
);

-- ============================================
-- MÓDULO FINANCIERO
-- ============================================

-- TABLA: TBL_SERVICIOS_MEDICOS
CREATE TABLE TBL_SERVICIOS_MEDICOS (
    ID_SERVICIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_SERVICIO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    APLICA_ISV BOOLEAN DEFAULT TRUE COMMENT 'Indica si este servicio aplica para el ISV (1=Gravado, 0=Exento).',
    CODIGO_CIEO_10 VARCHAR(20),
    CODIGO_CUPS VARCHAR(20),
    TIPO_SERVICIO ENUM('CONSULTA','EXAMEN','PROCEDIMIENTO','TERAPIA','HOSPITALIZACION') DEFAULT 'CONSULTA',
    CATEGORIA VARCHAR(100),
    ESTADO ENUM('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50),
    USUARIO_MODIFICACION VARCHAR(50),
    INDEX idx_servicio_tipo (TIPO_SERVICIO)
);
USE Roca_Maya;
-- TABLA: TBL_RECIBO (Recibo/Comprobante de Pago)
CREATE TABLE TBL_RECIBO (
    ID_RECIBO INT AUTO_INCREMENT PRIMARY KEY,
    ID_FACTURA INT NOT NULL,
    ID_PACIENTE INT NOT NULL,
    FECHA_RECIBO DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIPO_PAGO ENUM('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'CHEQUE', 'OTRO') NOT NULL,
    REFERENCIA_PAGO VARCHAR(100), -- No. de Cheque, No. de Tarjeta, Referencia de Transf.
    MONTO_PAGADO DECIMAL(10,2) NOT NULL CHECK (MONTO_PAGADO > 0),
    ESTADO_RECIBO ENUM('PENDIENTE', 'APLICADO', 'ANULADO') DEFAULT 'APLICADO',
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50) NOT NULL,
    USUARIO_MODIFICACION VARCHAR(50),
    
    FOREIGN KEY (ID_FACTURA) REFERENCES TBL_FACTURA(ID_FACTURA),
    FOREIGN KEY (ID_PACIENTE) REFERENCES TBL_PACIENTE(ID_PACIENTE),
    
    INDEX idx_recibo_factura (ID_FACTURA),
    INDEX idx_recibo_paciente (ID_PACIENTE),
    INDEX idx_recibo_estado (ESTADO_RECIBO)
);

-- TABLA: TBL_DETALLE_RECIBO (Detalle de Aplicación del Pago)
CREATE TABLE TBL_DETALLE_RECIBO (
    ID_DETALLE_RECIBO INT AUTO_INCREMENT PRIMARY KEY,
    ID_RECIBO INT NOT NULL,
    ID_DETALLE_FACTURA INT, -- Opcional, si se quiere detallar a qué línea de factura se aplicó el pago.
    MONTO_APLICADO DECIMAL(10,2) NOT NULL CHECK (MONTO_APLICADO > 0),
    DESCRIPCION VARCHAR(255),
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50),
    USUARIO_MODIFICACION VARCHAR(50),
    
    FOREIGN KEY (ID_RECIBO) REFERENCES TBL_RECIBO(ID_RECIBO) ON DELETE CASCADE,
    -- Si ID_DETALLE_FACTURA no es nulo, enlaza el detalle del pago al detalle de la factura.
    FOREIGN KEY (ID_DETALLE_FACTURA) REFERENCES TBL_DETALLE_FACTURA(ID_DETALLE_FACTURA),
    
    INDEX idx_detalle_recibo (ID_RECIBO)
);
-- ============================================
-- SISTEMA DE BITÁCORA COMPLETO - CORREGIDO
-- ============================================

-- TABLA: TBL_MS_BITACORA
CREATE TABLE TBL_MS_BITACORA (
    ID_BITACORA INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NULL, -- Cambiado a NULL para permitir registros sin usuario
    FECHA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    ACCION VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    MODULO VARCHAR(50),
    ID_REGISTRO_AFECTADO INT,
    TABLA_AFECTADA VARCHAR(50),
    IP_CLIENTE VARCHAR(45),
    USER_AGENT VARCHAR(500),
    ESTADO_OPERACION ENUM('EXITO','ERROR','ADVERTENCIA') DEFAULT 'EXITO',
    DETALLE_ERROR TEXT,
    -- Campos de auditoría
    USUARIO_CREACION VARCHAR(50),
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_MS_USUARIO(ID_USUARIO) ON DELETE SET NULL, -- Cambiado a SET NULL
    INDEX idx_bitacora_usuario (ID_USUARIO),
    INDEX idx_bitacora_fecha (FECHA_HORA),
    INDEX idx_bitacora_modulo (MODULO),
    INDEX idx_bitacora_accion (ACCION)
);

-- ============================================
-- PROCEDIMIENTOS ALMACENADOS MEJORADOS CON 2FA - CORREGIDOS
-- ============================================

DELIMITER //

-- Procedimiento para validar login según REQ001 - MEJORADO CON 2FA
CREATE PROCEDURE SP_VALIDAR_LOGIN(
    IN p_USUARIO VARCHAR(50),
    IN p_CONTRASENA VARCHAR(255)
)
BEGIN
    DECLARE v_ID_USUARIO INT;
    DECLARE v_ESTADO VARCHAR(20);
    DECLARE v_INTENTOS_FALLIDOS INT;
    DECLARE v_MAX_INTENTOS INT;
    DECLARE v_CONTRASENA_DB VARCHAR(255);
    DECLARE v_FECHA_VENCIMIENTO DATE;
    DECLARE v_ES_PRIMER_INGRESO BOOLEAN;
    DECLARE v_ACTIVO_2FA TINYINT(1);
    DECLARE v_BLOQUEO_2FA_HASTA DATETIME;
    
    -- Obtener parámetro de intentos máximos
    SELECT VALOR INTO v_MAX_INTENTOS FROM TBL_MS_PARAMETROS WHERE PARAMETRO = 'ADMIN_INTENTOS_INVALIDOS';
    IF v_MAX_INTENTOS IS NULL THEN SET v_MAX_INTENTOS = 3; END IF;
    
    -- Buscar usuario (en mayúsculas según REQ001)
    SELECT ID_USUARIO, ESTADO, INTENTOS_FALLIDOS, CONTRASENA, FECHA_VENCIMIENTO, ACTIVO_2FA, BLOQUEO_2FA_HASTA
    INTO v_ID_USUARIO, v_ESTADO, v_INTENTOS_FALLIDOS, v_CONTRASENA_DB, v_FECHA_VENCIMIENTO, v_ACTIVO_2FA, v_BLOQUEO_2FA_HASTA
    FROM TBL_MS_USUARIO 
    WHERE USUARIO = UPPER(p_USUARIO);
    
    IF v_ID_USUARIO IS NULL THEN
        -- Usuario no existe
        SELECT 'ERROR' AS RESULTADO, 'USUARIO/CONTRASEÑA INVÁLIDOS' AS MENSAJE, NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
    ELSE
        -- Verificar bloqueo por 2FA
        IF v_BLOQUEO_2FA_HASTA IS NOT NULL AND v_BLOQUEO_2FA_HASTA > NOW() THEN
            SELECT 'ERROR' AS RESULTADO, 
                   CONCAT('CUENTA BLOQUEADA POR INTENTOS FALLIDOS DE 2FA HASTA: ', 
                          DATE_FORMAT(v_BLOQUEO_2FA_HASTA, '%Y-%m-%d %H:%i:%s')) AS MENSAJE, 
                   NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
        ELSE
            -- Verificar estado del usuario
            IF v_ESTADO = 'BLOQUEADO' THEN
                SELECT 'ERROR' AS RESULTADO, 'USUARIO BLOQUEADO. CONTACTE AL ADMINISTRADOR.' AS MENSAJE, NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
            ELSEIF v_ESTADO = 'INACTIVO' THEN
                SELECT 'ERROR' AS RESULTADO, 'USUARIO INACTIVO. CONTACTE AL ADMINISTRADOR.' AS MENSAJE, NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
            ELSEIF v_INTENTOS_FALLIDOS >= v_MAX_INTENTOS THEN
                -- Bloquear usuario por exceso de intentos
                UPDATE TBL_MS_USUARIO SET ESTADO = 'BLOQUEADO' WHERE ID_USUARIO = v_ID_USUARIO;
                SELECT 'ERROR' AS RESULTADO, 'USUARIO BLOQUEADO POR EXCESO DE INTENTOS FALLIDOS.' AS MENSAJE, NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
            ELSEIF v_CONTRASENA_DB != p_CONTRASENA THEN
                -- Incrementar intentos fallidos
                UPDATE TBL_MS_USUARIO 
                SET INTENTOS_FALLIDOS = INTENTOS_FALLIDOS + 1,
                    FECHA_MODIFICACION = CURRENT_TIMESTAMP,
                    USUARIO_MODIFICACION = 'SISTEMA'
                WHERE ID_USUARIO = v_ID_USUARIO;
                
                SELECT 'ERROR' AS RESULTADO, 'USUARIO/CONTRASEÑA INVÁLIDOS' AS MENSAJE, NULL AS ID_USUARIO, FALSE AS REQUIERE_2FA;
            ELSE
                -- Login exitoso
                -- Reiniciar intentos fallidos y actualizar última conexión
                UPDATE TBL_MS_USUARIO 
                SET INTENTOS_FALLIDOS = 0,
                    INTENTOS_2FA_FALLIDOS = 0,
                    BLOQUEO_2FA_HASTA = NULL,
                    FECHA_ULTIMA_CONEXION = CURRENT_TIMESTAMP,
                    FECHA_MODIFICACION = CURRENT_TIMESTAMP,
                    USUARIO_MODIFICACION = 'SISTEMA'
                WHERE ID_USUARIO = v_ID_USUARIO;
                
                -- Verificar si es primer ingreso
                SET v_ES_PRIMER_INGRESO = (v_ESTADO = 'NUEVO');
                
                -- Si 2FA está activo, indicar que se requiere código
                IF v_ACTIVO_2FA = 1 THEN
                    SELECT 'REQUIERE_2FA' AS RESULTADO, 'SE REQUIERE CÓDIGO DE AUTENTICACIÓN DE DOS FACTORES' AS MENSAJE, 
                           v_ID_USUARIO AS ID_USUARIO, TRUE AS REQUIERE_2FA;
                ELSE
                    SELECT 'EXITO' AS RESULTADO, 'LOGIN EXITOSO' AS MENSAJE, v_ID_USUARIO AS ID_USUARIO, 
                           FALSE AS REQUIERE_2FA, v_ES_PRIMER_INGRESO AS PRIMER_INGRESO;
                END IF;
            END IF;
        END IF;
    END IF;
END //

-- Procedimiento para validar código 2FA
CREATE PROCEDURE SP_VALIDAR_CODIGO_2FA(
    IN p_ID_USUARIO INT,
    IN p_CODIGO_2FA VARCHAR(10)
)
BEGIN
    DECLARE v_MAX_INTENTOS_2FA INT;
    DECLARE v_TIEMPO_BLOQUEO_MIN INT;
    DECLARE v_INTENTOS_2FA_FALLIDOS INT;
    DECLARE v_SECRET_2FA VARCHAR(255);
    DECLARE v_ACTIVO_2FA TINYINT(1);
    
    -- Obtener parámetros de 2FA
    SELECT VALOR INTO v_MAX_INTENTOS_2FA FROM TBL_MS_PARAMETROS WHERE PARAMETRO = '2FA_MAX_INTENTOS';
    IF v_MAX_INTENTOS_2FA IS NULL THEN SET v_MAX_INTENTOS_2FA = 3; END IF;
    
    SELECT VALOR INTO v_TIEMPO_BLOQUEO_MIN FROM TBL_MS_PARAMETROS WHERE PARAMETRO = '2FA_TIEMPO_BLOQUEO_MIN';
    IF v_TIEMPO_BLOQUEO_MIN IS NULL THEN SET v_TIEMPO_BLOQUEO_MIN = 30; END IF;
    
    -- Obtener datos del usuario
    SELECT INTENTOS_2FA_FALLIDOS, SECRET_2FA, ACTIVO_2FA
    INTO v_INTENTOS_2FA_FALLIDOS, v_SECRET_2FA, v_ACTIVO_2FA
    FROM TBL_MS_USUARIO 
    WHERE ID_USUARIO = p_ID_USUARIO;
    
    -- Verificar si 2FA está activo
    IF v_ACTIVO_2FA != 1 THEN
        SELECT 'ERROR' AS RESULTADO, '2FA NO ESTÁ ACTIVADO PARA ESTE USUARIO' AS MENSAJE;
    ELSEIF v_INTENTOS_2FA_FALLIDOS >= v_MAX_INTENTOS_2FA THEN
        -- Bloquear usuario por exceso de intentos 2FA
        UPDATE TBL_MS_USUARIO 
        SET BLOQUEO_2FA_HASTA = DATE_ADD(NOW(), INTERVAL v_TIEMPO_BLOQUEO_MIN MINUTE),
            FECHA_MODIFICACION = CURRENT_TIMESTAMP,
            USUARIO_MODIFICACION = 'SISTEMA'
        WHERE ID_USUARIO = p_ID_USUARIO;
        
        SELECT 'ERROR' AS RESULTADO, 
               CONCAT('CUENTA BLOQUEADA POR EXCESO DE INTENTOS 2FA. ESPERE ', v_TIEMPO_BLOQUEO_MIN, ' MINUTOS.') AS MENSAJE;
    ELSE
        -- Aquí se integraría la validación real del código TOTP
        -- Por ahora, simulamos una validación básica (en producción usarías una librería TOTP)
        IF LENGTH(p_CODIGO_2FA) = 6 AND p_CODIGO_2FA REGEXP '^[0-9]+$' THEN
            -- Código válido (simulación)
            UPDATE TBL_MS_USUARIO 
            SET INTENTOS_2FA_FALLIDOS = 0,
                BLOQUEO_2FA_HASTA = NULL,
                ULTIMO_CODIGO_2FA = p_CODIGO_2FA,
                FECHA_MODIFICACION = CURRENT_TIMESTAMP,
                USUARIO_MODIFICACION = 'SISTEMA'
            WHERE ID_USUARIO = p_ID_USUARIO;
            
            -- Registrar en bitácora
            CALL SP_REGISTRAR_BITACORA(
                p_ID_USUARIO,
                'VALIDACION_2FA_EXITOSA',
                'Validación de código 2FA exitosa',
                'AUTENTICACION',
                p_ID_USUARIO,
                'TBL_MS_USUARIO',
                NULL, NULL, 'EXITO', NULL,
                'SISTEMA'
            );
            
            SELECT 'EXITO' AS RESULTADO, 'CÓDIGO 2FA VÁLIDO' AS MENSAJE;
        ELSE
            -- Código inválido
            UPDATE TBL_MS_USUARIO 
            SET INTENTOS_2FA_FALLIDOS = v_INTENTOS_2FA_FALLIDOS + 1,
                FECHA_MODIFICACION = CURRENT_TIMESTAMP,
                USUARIO_MODIFICACION = 'SISTEMA'
            WHERE ID_USUARIO = p_ID_USUARIO;
            
            -- Registrar en bitácora
            CALL SP_REGISTRAR_BITACORA(
                p_ID_USUARIO,
                'VALIDACION_2FA_FALLIDA',
                'Intento fallido de validación de código 2FA',
                'AUTENTICACION',
                p_ID_USUARIO,
                'TBL_MS_USUARIO',
                NULL, NULL, 'ERROR', 'Código 2FA inválido',
                'SISTEMA'
            );
            
            SELECT 'ERROR' AS RESULTADO, 'CÓDIGO 2FA INVÁLIDO' AS MENSAJE;
        END IF;
    END IF;
END //

-- Procedimiento para activar 2FA
CREATE PROCEDURE SP_ACTIVAR_2FA(
    IN p_ID_USUARIO INT,
    IN p_SECRET_2FA VARCHAR(255),
    IN p_USUARIO_ACTUALIZACION VARCHAR(50)
)
BEGIN
    UPDATE TBL_MS_USUARIO 
    SET SECRET_2FA = p_SECRET_2FA,
        ACTIVO_2FA = 1,
        FECHA_ACTIVACION_2FA = CURRENT_TIMESTAMP,
        FECHA_MODIFICACION = CURRENT_TIMESTAMP,
        USUARIO_MODIFICACION = p_USUARIO_ACTUALIZACION
    WHERE ID_USUARIO = p_ID_USUARIO;
    
    -- Registrar en bitácora
    CALL SP_REGISTRAR_BITACORA(
        p_ID_USUARIO,
        'ACTIVACION_2FA',
        'Usuario activó autenticación de dos factores',
        'SEGURIDAD',
        p_ID_USUARIO,
        'TBL_MS_USUARIO',
        NULL, NULL, 'EXITO', NULL,
        p_USUARIO_ACTUALIZACION
    );
    
    SELECT 'EXITO' AS RESULTADO, '2FA ACTIVADO CORRECTAMENTE' AS MENSAJE;
END //

-- Procedimiento para desactivar 2FA
CREATE PROCEDURE SP_DESACTIVAR_2FA(
    IN p_ID_USUARIO INT,
    IN p_USUARIO_ACTUALIZACION VARCHAR(50)
)
BEGIN
    UPDATE TBL_MS_USUARIO 
    SET ACTIVO_2FA = 0,
        SECRET_2FA = NULL,
        INTENTOS_2FA_FALLIDOS = 0,
        BLOQUEO_2FA_HASTA = NULL,
        FECHA_MODIFICACION = CURRENT_TIMESTAMP,
        USUARIO_MODIFICACION = p_USUARIO_ACTUALIZACION
    WHERE ID_USUARIO = p_ID_USUARIO;
    
    -- Registrar en bitácora
    CALL SP_REGISTRAR_BITACORA(
        p_ID_USUARIO,
        'DESACTIVACION_2FA',
        'Usuario desactivó autenticación de dos factores',
        'SEGURIDAD',
        p_ID_USUARIO,
        'TBL_MS_USUARIO',
        NULL, NULL, 'EXITO', NULL,
        p_USUARIO_ACTUALIZACION
    );
    
    SELECT 'EXITO' AS RESULTADO, '2FA DESACTIVADO CORRECTAMENTE' AS MENSAJE;
END //

-- Procedimiento para registrar en bitácora - CORREGIDO
CREATE PROCEDURE SP_REGISTRAR_BITACORA(
    IN p_ID_USUARIO INT,
    IN p_ACCION VARCHAR(100),
    IN p_DESCRIPCION TEXT,
    IN p_MODULO VARCHAR(50),
    IN p_ID_REGISTRO_AFECTADO INT,
    IN p_TABLA_AFECTADA VARCHAR(50),
    IN p_IP_CLIENTE VARCHAR(45),
    IN p_USER_AGENT VARCHAR(500),
    IN p_ESTADO_OPERACION ENUM('EXITO','ERROR','ADVERTENCIA'),
    IN p_DETALLE_ERROR TEXT,
    IN p_USUARIO_CREACION VARCHAR(50)
)
BEGIN
    DECLARE v_usuario_valido INT DEFAULT NULL;
    
    -- Verificar si el ID_USUARIO existe
    IF p_ID_USUARIO IS NOT NULL THEN
        SELECT ID_USUARIO INTO v_usuario_valido 
        FROM TBL_MS_USUARIO 
        WHERE ID_USUARIO = p_ID_USUARIO;
    END IF;
    
    -- Si no existe el usuario, usar NULL
    IF v_usuario_valido IS NULL THEN
        SET p_ID_USUARIO = NULL;
    END IF;
    
    INSERT INTO TBL_MS_BITACORA (
        ID_USUARIO, ACCION, DESCRIPCION, MODULO, 
        ID_REGISTRO_AFECTADO, TABLA_AFECTADA, IP_CLIENTE, USER_AGENT,
        ESTADO_OPERACION, DETALLE_ERROR, USUARIO_CREACION
    ) VALUES (
        p_ID_USUARIO, p_ACCION, p_DESCRIPCION, p_MODULO,
        p_ID_REGISTRO_AFECTADO, p_TABLA_AFECTADA, p_IP_CLIENTE, p_USER_AGENT,
        p_ESTADO_OPERACION, p_DETALLE_ERROR, p_USUARIO_CREACION
    );
END //

-- Procedimiento para consultar bitácora
CREATE PROCEDURE SP_CONSULTAR_BITACORA(
    IN p_FECHA_INICIO DATETIME,
    IN p_FECHA_FIN DATETIME,
    IN p_ID_USUARIO INT,
    IN p_MODULO VARCHAR(50),
    IN p_ACCION VARCHAR(100)
)
BEGIN
    SELECT 
        b.ID_BITACORA,
        b.FECHA_HORA,
        COALESCE(u.USUARIO, 'SISTEMA') AS USUARIO,
        COALESCE(u.NOMBRE_USUARIO, 'SISTEMA') AS NOMBRE_USUARIO,
        b.ACCION,
        b.DESCRIPCION,
        b.MODULO,
        b.TABLA_AFECTADA,
        b.ID_REGISTRO_AFECTADO,
        b.IP_CLIENTE,
        b.ESTADO_OPERACION,
        b.DETALLE_ERROR
    FROM TBL_MS_BITACORA b
    LEFT JOIN TBL_MS_USUARIO u ON b.ID_USUARIO = u.ID_USUARIO
    WHERE 
        (p_FECHA_INICIO IS NULL OR b.FECHA_HORA >= p_FECHA_INICIO) AND
        (p_FECHA_FIN IS NULL OR b.FECHA_HORA <= p_FECHA_FIN) AND
        (p_ID_USUARIO IS NULL OR b.ID_USUARIO = p_ID_USUARIO) AND
        (p_MODULO IS NULL OR b.MODULO = p_MODULO) AND
        (p_ACCION IS NULL OR b.ACCION = p_ACCION)
    ORDER BY b.FECHA_HORA DESC;
END //

DELIMITER ;

-- ============================================
-- TRIGGERS PARA AUDITORÍA AUTOMÁTICA - CORREGIDOS
-- ============================================

DELIMITER //

-- Trigger para auditoría de creación de pacientes
CREATE TRIGGER TR_AUDITORIA_PACIENTES_INSERT
AFTER INSERT ON TBL_PACIENTE
FOR EACH ROW
BEGIN
    CALL SP_REGISTRAR_BITACORA(
        COALESCE(NEW.ID_USUARIO_REGISTRO, 1),
        'CREACION_PACIENTE',
        CONCAT('Nuevo paciente creado: ', NEW.NOMBRES, ' ', NEW.APELLIDOS, ' (', NEW.NUMERO_DOCUMENTO_IDENTIDAD, ')'),
        'PACIENTES',
        NEW.ID_PACIENTE,
        'TBL_PACIENTE',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END //

-- Trigger para auditoría de actualización de pacientes
CREATE TRIGGER TR_AUDITORIA_PACIENTES_UPDATE
AFTER UPDATE ON TBL_PACIENTE
FOR EACH ROW
BEGIN
    CALL SP_REGISTRAR_BITACORA(
        COALESCE(NEW.ID_USUARIO_REGISTRO, 1),
        'ACTUALIZACION_PACIENTE',
        CONCAT('Paciente actualizado: ', NEW.NOMBRES, ' ', NEW.APELLIDOS),
        'PACIENTES',
        NEW.ID_PACIENTE,
        'TBL_PACIENTE',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END //

-- Trigger para auditoría de citas
CREATE TRIGGER TR_AUDITORIA_CITAS_INSERT
AFTER INSERT ON TBL_CITAS
FOR EACH ROW
BEGIN
    CALL SP_REGISTRAR_BITACORA(
        COALESCE(NEW.ID_USUARIOCREADOR, 1),
        'CREACION_CITA',
        CONCAT('Cita creada para paciente ID: ', NEW.ID_PACIENTE, ' con doctor ID: ', NEW.ID_DOCTOR, ' - ', NEW.ESTADO),
        'CITAS',
        NEW.ID_CITA,
        'TBL_CITAS',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END //

-- Trigger para cambios de estado en citas
CREATE TRIGGER TR_AUDITORIA_CITAS_UPDATE
AFTER UPDATE ON TBL_CITAS
FOR EACH ROW
BEGIN
    IF OLD.ESTADO != NEW.ESTADO THEN
        CALL SP_REGISTRAR_BITACORA(
            COALESCE((SELECT ID_USUARIO FROM TBL_MS_USUARIO WHERE USUARIO = COALESCE(NEW.USUARIO_MODIFICACION, 'SISTEMA')), 1),
            'CAMBIO_ESTADO_CITA',
            CONCAT('Cita ID ', NEW.ID_CITA, ' cambió de ', OLD.ESTADO, ' a ', NEW.ESTADO),
            'CITAS',
            NEW.ID_CITA,
            'TBL_CITAS',
            NULL, NULL, 'EXITO', NULL,
            'TRIGGER'
        );
    END IF;
END //

-- Trigger para auditoría de consultas médicas
CREATE TRIGGER TR_AUDITORIA_CONSULTAS_INSERT
AFTER INSERT ON TBL_CONSULTA_MEDICA
FOR EACH ROW
BEGIN
    CALL SP_REGISTRAR_BITACORA(
        COALESCE(NEW.ID_DOCTOR, 1),
        'REGISTRO_CONSULTA',
        CONCAT('Consulta médica registrada para paciente ID: ', NEW.ID_PACIENTE, ' - Diagnóstico: ', COALESCE(LEFT(NEW.DIAGNOSTICO_PRINCIPAL, 50), 'SIN DIAGNÓSTICO')),
        'CONSULTAS',
        NEW.ID_CONSULTA,
        'TBL_CONSULTA_MEDICA',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END //

-- Trigger para auditoría de prescripciones
CREATE TRIGGER TR_AUDITORIA_PRESCRIPCIONES_INSERT
AFTER INSERT ON TBL_PRESCRIPCION
FOR EACH ROW
BEGIN
    DECLARE v_medicamento_nombre VARCHAR(255);
    DECLARE v_id_doctor INT;
    
    -- Obtener nombre del medicamento
    SELECT COALESCE(NOMBRE_MEDICAMENTO, 'MEDICAMENTO DESCONOCIDO') INTO v_medicamento_nombre 
    FROM TBL_INVENTARIO_MEDICAMENTO 
    WHERE ID_MEDICAMENTO = NEW.ID_MEDICAMENTO;
    
    -- Obtener ID del doctor
    SELECT COALESCE(ID_DOCTOR, 1) INTO v_id_doctor 
    FROM TBL_CONSULTA_MEDICA 
    WHERE ID_CONSULTA = NEW.ID_CONSULTA;
    
    CALL SP_REGISTRAR_BITACORA(
        v_id_doctor,
        'PRESCRIPCION_MEDICA',
        CONCAT('Prescripción de ', v_medicamento_nombre, ' - Dosis: ', NEW.DOSIS),
        'FARMACIA',
        NEW.ID_PRESCRIPCION,
        'TBL_PRESCRIPCION',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END //

-- Trigger para auditoría de activación/desactivación de 2FA
CREATE TRIGGER TR_AUDITORIA_2FA_UPDATE
AFTER UPDATE ON TBL_MS_USUARIO
FOR EACH ROW
BEGIN
    IF OLD.ACTIVO_2FA != NEW.ACTIVO_2FA THEN
        IF NEW.ACTIVO_2FA = 1 THEN
            CALL SP_REGISTRAR_BITACORA(
                NEW.ID_USUARIO,
                'ACTIVACION_2FA',
                'Usuario activó autenticación de dos factores',
                'SEGURIDAD',
                NEW.ID_USUARIO,
                'TBL_MS_USUARIO',
                NULL, NULL, 'EXITO', NULL,
                'TRIGGER'
            );
        ELSE
            CALL SP_REGISTRAR_BITACORA(
                NEW.ID_USUARIO,
                'DESACTIVACION_2FA',
                'Usuario desactivó autenticación de dos factores',
                'SEGURIDAD',
                NEW.ID_USUARIO,
                'TBL_MS_USUARIO',
                NULL, NULL, 'EXITO', NULL,
                'TRIGGER'
            );
        END IF;
    END IF;
END //

-- ============================================
-- TRIGGERS COMPLETOS PARA BITÁCORA AUTOMÁTICA - CORREGIDOS
-- ============================================

DELIMITER //

-- Trigger para auditoría de creación de usuarios
CREATE TRIGGER TR_AUDITORIA_USUARIOS_INSERT
AFTER INSERT ON TBL_MS_USUARIO
FOR EACH ROW
BEGIN
    DECLARE v_id_usuario_creador INT;
    
    -- Buscar ID del usuario creador
    SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_creador 
    FROM TBL_MS_USUARIO 
    WHERE USUARIO = COALESCE(NEW.USUARIO_CREACION, 'SISTEMA')
    LIMIT 1;
    
    CALL SP_REGISTRAR_BITACORA(
        v_id_usuario_creador,
        'CREACION_USUARIO',
        CONCAT('Nuevo usuario creado: ', NEW.USUARIO, ' - ', NEW.NOMBRE_USUARIO),
        'USUARIOS',
        NEW.ID_USUARIO,
        'TBL_MS_USUARIO',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END //

-- Trigger para auditoría de actualización de usuarios
CREATE TRIGGER TR_AUDITORIA_USUARIOS_UPDATE
AFTER UPDATE ON TBL_MS_USUARIO
FOR EACH ROW
BEGIN
    DECLARE v_cambios TEXT DEFAULT '';
    DECLARE v_id_usuario_modificador INT;
    
    -- Buscar ID del usuario modificador
    SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_modificador 
    FROM TBL_MS_USUARIO 
    WHERE USUARIO = COALESCE(NEW.USUARIO_MODIFICACION, 'SISTEMA')
    LIMIT 1;
    
    -- Detectar cambios específicos
    IF OLD.ESTADO != NEW.ESTADO THEN
        SET v_cambios = CONCAT(v_cambios, 'Estado: ', OLD.ESTADO, ' → ', NEW.ESTADO, '; ');
    END IF;
    
    IF OLD.INTENTOS_FALLIDOS != NEW.INTENTOS_FALLIDOS THEN
        SET v_cambios = CONCAT(v_cambios, 'Intentos: ', OLD.INTENTOS_FALLIDOS, ' → ', NEW.INTENTOS_FALLIDOS, '; ');
    END IF;
    
    IF OLD.ACTIVO_2FA != NEW.ACTIVO_2FA THEN
        SET v_cambios = CONCAT(v_cambios, '2FA: ', OLD.ACTIVO_2FA, ' → ', NEW.ACTIVO_2FA, '; ');
    END IF;
    
    IF v_cambios = '' THEN
        SET v_cambios = 'Actualización general del usuario';
    END IF;
    
    CALL SP_REGISTRAR_BITACORA(
        v_id_usuario_modificador,
        'ACTUALIZACION_USUARIO',
        CONCAT('Usuario actualizado: ', NEW.USUARIO, ' - Cambios: ', v_cambios),
        'USUARIOS',
        NEW.ID_USUARIO,
        'TBL_MS_USUARIO',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END //

-- Trigger para auditoría de roles
CREATE TRIGGER TR_AUDITORIA_ROLES_INSERT
AFTER INSERT ON TBL_MS_ROLES
FOR EACH ROW
BEGIN
    DECLARE v_id_usuario_creador INT;
    
    -- Buscar ID del usuario creador
    SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_creador 
    FROM TBL_MS_USUARIO 
    WHERE USUARIO = COALESCE(NEW.USUARIO_CREACION, 'SISTEMA')
    LIMIT 1;
    
    CALL SP_REGISTRAR_BITACORA(
        v_id_usuario_creador,
        'CREACION_ROL',
        CONCAT('Nuevo rol creado: ', NEW.ROL),
        'ROLES',
        NEW.ID_ROL,
        'TBL_MS_ROLES',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END //

-- Trigger para auditoría de parámetros del sistema
CREATE TRIGGER TR_AUDITORIA_PARAMETROS_UPDATE
AFTER UPDATE ON TBL_MS_PARAMETROS
FOR EACH ROW
BEGIN
    DECLARE v_id_usuario_modificador INT;
    
    IF OLD.VALOR != NEW.VALOR THEN
        -- Buscar ID del usuario modificador
        SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_modificador 
        FROM TBL_MS_USUARIO 
        WHERE USUARIO = COALESCE(NEW.USUARIO_MODIFICACION, 'SISTEMA')
        LIMIT 1;
        
        CALL SP_REGISTRAR_BITACORA(
            v_id_usuario_modificador,
            'ACTUALIZACION_PARAMETRO',
            CONCAT('Parámetro actualizado: ', NEW.PARAMETRO, ' - Valor: ', OLD.VALOR, ' → ', NEW.VALOR),
            'CONFIGURACION',
            NEW.ID_PARAMETRO,
            'TBL_MS_PARAMETROS',
            NULL, NULL, 'EXITO', NULL,
            'TRIGGER'
        );
    END IF;
END //

-- Trigger para auditoría de medicamentos
CREATE TRIGGER TR_AUDITORIA_MEDICAMENTOS_INSERT
AFTER INSERT ON TBL_INVENTARIO_MEDICAMENTO
FOR EACH ROW
BEGIN
    CALL SP_REGISTRAR_BITACORA(
        COALESCE(NEW.ID_USUARIO_REGISTRO, 1),
        'CREACION_MEDICAMENTO',
        CONCAT('Medicamento agregado: ', NEW.NOMBRE_MEDICAMENTO, ' - Stock: ', NEW.STOCK_ACTUAL),
        'FARMACIA',
        NEW.ID_MEDICAMENTO,
        'TBL_INVENTARIO_MEDICAMENTO',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END //

-- Trigger para auditoría de actualización de medicamentos
CREATE TRIGGER TR_AUDITORIA_MEDICAMENTOS_UPDATE
AFTER UPDATE ON TBL_INVENTARIO_MEDICAMENTO
FOR EACH ROW
BEGIN
    DECLARE v_cambios TEXT DEFAULT '';
    DECLARE v_id_usuario_modificador INT;
    
    IF OLD.STOCK_ACTUAL != NEW.STOCK_ACTUAL THEN
        SET v_cambios = CONCAT(v_cambios, 'Stock: ', OLD.STOCK_ACTUAL, ' → ', NEW.STOCK_ACTUAL, '; ');
    END IF;
    
    IF OLD.PRECIO_VENTA != NEW.PRECIO_VENTA THEN
        SET v_cambios = CONCAT(v_cambios, 'Precio: ', OLD.PRECIO_VENTA, ' → ', NEW.PRECIO_VENTA, '; ');
    END IF;
    
    IF OLD.ESTADO != NEW.ESTADO THEN
        SET v_cambios = CONCAT(v_cambios, 'Estado: ', OLD.ESTADO, ' → ', NEW.ESTADO, '; ');
    END IF;
    
    IF v_cambios != '' THEN
        -- Buscar ID del usuario modificador
        SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_modificador 
        FROM TBL_MS_USUARIO 
        WHERE USUARIO = COALESCE(NEW.USUARIO_MODIFICACION, 'SISTEMA')
        LIMIT 1;
        
        CALL SP_REGISTRAR_BITACORA(
            v_id_usuario_modificador,
            'ACTUALIZACION_MEDICAMENTO',
            CONCAT('Medicamento actualizado: ', NEW.NOMBRE_MEDICAMENTO, ' - Cambios: ', v_cambios),
            'FARMACIA',
            NEW.ID_MEDICAMENTO,
            'TBL_INVENTARIO_MEDICAMENTO',
            NULL, NULL, 'EXITO', NULL,
            'TRIGGER'
        );
    END IF;
END //

-- Trigger para auditoría de facturas
CREATE TRIGGER TR_AUDITORIA_FACTURAS_INSERT
AFTER INSERT ON TBL_FACTURA
FOR EACH ROW
BEGIN
    DECLARE v_id_usuario_creador INT;
    
    -- Buscar ID del usuario creador
    SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_creador 
    FROM TBL_MS_USUARIO 
    WHERE USUARIO = COALESCE(NEW.USUARIO_CREACION, 'SISTEMA')
    LIMIT 1;
    
    CALL SP_REGISTRAR_BITACORA(
        v_id_usuario_creador,
        'CREACION_FACTURA',
        CONCAT('Factura creada: ', NEW.NUMERO_FACTURA, ' - Monto: L', NEW.MONTO_TOTAL),
        'FACTURACION',
        NEW.ID_FACTURA,
        'TBL_FACTURA',
        NULL, NULL, 'EXITO', NULL,
        'TRIGGER'
    );
END //

-- Trigger para auditoría de cambios de estado en facturas
CREATE TRIGGER TR_AUDITORIA_FACTURAS_UPDATE
AFTER UPDATE ON TBL_FACTURA
FOR EACH ROW
BEGIN
    DECLARE v_id_usuario_modificador INT;
    
    IF OLD.ESTADO_FACTURA != NEW.ESTADO_FACTURA THEN
        -- Buscar ID del usuario modificador
        SELECT COALESCE(ID_USUARIO, 1) INTO v_id_usuario_modificador 
        FROM TBL_MS_USUARIO 
        WHERE USUARIO = COALESCE(NEW.USUARIO_MODIFICACION, 'SISTEMA')
        LIMIT 1;
        
        CALL SP_REGISTRAR_BITACORA(
            v_id_usuario_modificador,
            'CAMBIO_ESTADO_FACTURA',
            CONCAT('Factura ', NEW.NUMERO_FACTURA, ' cambió de ', OLD.ESTADO_FACTURA, ' a ', NEW.ESTADO_FACTURA),
            'FACTURACION',
            NEW.ID_FACTURA,
            'TBL_FACTURA',
            NULL, NULL, 'EXITO', NULL,
            'TRIGGER'
        );
    END IF;
END //

DELIMITER ;

-- ============================================
-- VISTAS DEL SISTEMA MEJORADAS - CORREGIDAS
-- ============================================

-- Vista para usuarios con información completa (MEJORADA CON 2FA)
CREATE VIEW VW_USUARIOS_COMPLETOS AS
SELECT 
    u.ID_USUARIO,
    u.USUARIO,
    u.NOMBRE_USUARIO,
    u.ESTADO,
    u.CORREO_ELECTRONICO,
    u.FECHA_ULTIMA_CONEXION,
    u.FECHA_VENCIMIENTO,
    u.INTENTOS_FALLIDOS,
    u.ACTIVO_2FA,
    u.FECHA_ACTIVACION_2FA,
    u.INTENTOS_2FA_FALLIDOS,
    u.BLOQUEO_2FA_HASTA,
    r.ROL,
    r.DESCRIPCION AS DESCRIPCION_ROL
FROM TBL_MS_USUARIO u
INNER JOIN TBL_MS_ROLES r ON u.ID_ROL = r.ID_ROL;

-- Vista para citas con información completa
CREATE VIEW VW_CITAS_COMPLETAS AS
SELECT 
    c.ID_CITA,
    c.FECHA_CITA,
    c.FECHA_FIN_ESTIMADA,
    c.ESTADO AS ESTADO_CITA,
    c.PRIORIDAD,
    c.TIPO_CITA,
    p.ID_PACIENTE,
    CONCAT(p.NOMBRES, ' ', p.APELLIDOS) AS NOMBRE_PACIENTE,
    p.TELEFONO,
    p.CORREO_ELECTRONICO,
    u.ID_USUARIO AS ID_DOCTOR,
    u.NOMBRE_USUARIO AS NOMBRE_DOCTOR,
    COALESCE(e.NOMBRE_ESPECIALIDAD, 'SIN ESPECIALIDAD') AS NOMBRE_ESPECIALIDAD,
    c.MOTIVO_CONSULTA,
    c.OBSERVACIONES
FROM TBL_CITAS c
INNER JOIN TBL_PACIENTE p ON c.ID_PACIENTE = p.ID_PACIENTE
INNER JOIN TBL_MS_USUARIO u ON c.ID_DOCTOR = u.ID_USUARIO
LEFT JOIN TBL_DOCTOR_ESPECIALIDAD de ON u.ID_USUARIO = de.ID_DOCTOR AND de.ES_PRIMARIA = TRUE
LEFT JOIN TBL_ESPECIALIDADES e ON de.ID_ESPECIALIDAD = e.ID_ESPECIALIDAD;

-- Vista para bitácora con información completa - CORREGIDA
CREATE VIEW VW_BITACORA_COMPLETA AS
SELECT 
    b.ID_BITACORA,
    b.FECHA_HORA,
    COALESCE(u.USUARIO, 'SISTEMA') AS USUARIO,
    COALESCE(u.NOMBRE_USUARIO, 'SISTEMA') AS NOMBRE_USUARIO,
    COALESCE(r.ROL, 'SISTEMA') AS ROL,
    b.ACCION,
    b.DESCRIPCION,
    b.MODULO,
    b.TABLA_AFECTADA,
    b.ID_REGISTRO_AFECTADO,
    b.IP_CLIENTE,
    b.ESTADO_OPERACION,
    b.DETALLE_ERROR,
    b.USER_AGENT
FROM TBL_MS_BITACORA b
LEFT JOIN TBL_MS_USUARIO u ON b.ID_USUARIO = u.ID_USUARIO
LEFT JOIN TBL_MS_ROLES r ON u.ID_ROL = r.ID_ROL;

-- Vista para estadísticas de bitácora
CREATE VIEW VW_ESTADISTICAS_BITACORA AS
SELECT 
    DATE(FECHA_HORA) AS FECHA,
    MODULO,
    ESTADO_OPERACION,
    COUNT(*) AS TOTAL_OPERACIONES,
    COUNT(DISTINCT ID_USUARIO) AS USUARIOS_ACTIVOS
FROM TBL_MS_BITACORA
GROUP BY DATE(FECHA_HORA), MODULO, ESTADO_OPERACION;

-- Vista para estado de seguridad 2FA
CREATE VIEW VW_ESTADO_SEGURIDAD_2FA AS
SELECT 
    u.ID_USUARIO,
    u.USUARIO,
    u.NOMBRE_USUARIO,
    u.ACTIVO_2FA,
    u.FECHA_ACTIVACION_2FA,
    u.INTENTOS_2FA_FALLIDOS,
    u.BLOQUEO_2FA_HASTA,
    r.ROL,
    CASE 
        WHEN u.ACTIVO_2FA = 1 THEN 'PROTEGIDO'
        ELSE 'VULNERABLE'
    END AS ESTADO_SEGURIDAD
FROM TBL_MS_USUARIO u
INNER JOIN TBL_MS_ROLES r ON u.ID_ROL = r.ID_ROL;

-- ============================================
-- DATOS INICIALES SEGÚN REQUERIMIENTO - MEJORADOS
-- ============================================

-- Insertar Roles básicos
INSERT INTO TBL_MS_ROLES (ROL, DESCRIPCION, USUARIO_CREACION) VALUES
('ADMINISTRADOR', 'USUARIO CON ACCESO COMPLETO AL SISTEMA', 'SISTEMA'),
('DOCTOR', 'MÉDICO CON PERMISOS PARA CONSULTAS Y RECETAS', 'SISTEMA'),
('ENFERMERA', 'PERSONAL DE ENFERMERÍA PARA PRECLÍNICA', 'SISTEMA'),
('RECEPCIONISTA', 'PERSONAL DE RECEPCIÓN Y CITAS', 'SISTEMA'),
('PACIENTE', 'USUARIO PACIENTE DEL SISTEMA', 'SISTEMA');

-- Insertar Parámetros mínimos requeridos según documento - MEJORADOS CON 2FA
INSERT INTO TBL_MS_PARAMETROS (PARAMETRO, VALOR, DESCRIPCION, USUARIO_CREACION) VALUES
('ADMIN_INTENTOS_INVALIDOS', '3', 'NÚMERO MÁXIMO DE INTENTOS DE LOGIN FALLIDOS PERMITIDOS', 'SISTEMA'),
('ADMIN_PREGUNTAS', '3', 'NÚMERO DE PREGUNTAS DE SEGURIDAD REQUERIDAS', 'SISTEMA'),
('ADMIN_CORREO', 'correo@dominio.com', 'CORREO ELECTRÓNICO PARA ENVÍO DE NOTIFICACIONES', 'SISTEMA'),
('ADMIN_CPUERTO', '9999', 'PUERTO PARA CONFIGURACIÓN DEL SERVIDOR', 'SISTEMA'),
('ADMIN_CUSER', 'USUARIO', 'USUARIO PARA CONFIGURACIÓN DEL SERVIDOR', 'SISTEMA'),
('ADMIN_CPASS', 'PASSWORD', 'CONTRASEÑA PARA CONFIGURACIÓN DEL SERVIDOR', 'SISTEMA'),
('ADMIN_VIGENCIA', '30', 'DÍAS DE VIGENCIA DE LA CONTRASEÑA', 'SISTEMA'),
('ADMIN_DIAS_VIGENCIA', '360', 'DÍAS DE VIGENCIA DE LA CUENTA DE USUARIO', 'SISTEMA'),
('IMPUESTO', '15', 'PORCENTAJE DE IMPUESTO APLICABLE', 'SISTEMA'),
('SYS_NOMBRE', 'SISTEMA ROCA MAYA', 'NOMBRE DEL SISTEMA', 'SISTEMA'),
('MIN_CONTRASEÑA', '8', 'LONGITUD MÍNIMA DE LA CONTRASEÑA', 'SISTEMA'),
('MAX_CONTRASEÑA', '15', 'LONGITUD MÁXIMA DE LA CONTRASEÑA', 'SISTEMA'),
('BITACORA_RETENCION_DIAS', '365', 'DÍAS DE RETENCIÓN DE REGISTROS EN BITÁCORA', 'SISTEMA'),
('BITACORA_LOG_ERRORS', 'SI', 'REGISTRAR ERRORES EN BITÁCORA (SI/NO)', 'SISTEMA'),
('BITACORA_LOG_LOGINS', 'SI', 'REGISTRAR INICIOS DE SESIÓN EN BITÁCORA', 'SISTEMA'),
('2FA_MAX_INTENTOS', '3', 'MÁXIMO DE INTENTOS FALLIDOS DE CÓDIGO 2FA', 'SISTEMA'),
('2FA_TIEMPO_BLOQUEO_MIN', '30', 'MINUTOS DE BLOQUEO POR INTENTOS FALLIDOS 2FA', 'SISTEMA'),
('2FA_OBLIGATORIO_ADMIN', 'SI', '2FA OBLIGATORIO PARA USUARIOS ADMINISTRADORES', 'SISTEMA');

-- Insertar Especialidades médicas
INSERT INTO TBL_ESPECIALIDADES (NOMBRE_ESPECIALIDAD, DESCRIPCION, USUARIO_CREACION) VALUES
('MEDICINA GENERAL', 'ATENCIÓN PRIMARIA Y GENERAL', 'SISTEMA'),
('PEDIATRÍA', 'ESPECIALIDAD EN NIÑOS', 'SISTEMA'),
('GINECOLOGÍA', 'SALUD FEMENINA', 'SISTEMA'),
('CARDIOLOGÍA', 'ESPECIALIDAD DEL CORAZÓN', 'SISTEMA'),
('DERMATOLOGÍA', 'ESPECIALIDAD DE LA PIEL', 'SISTEMA');

-- Insertar Servicios médicos básicos
INSERT INTO TBL_SERVICIOS_MEDICOS (NOMBRE_SERVICIO, DESCRIPCION, PRECIO_UNITARIO, TIPO_SERVICIO, USUARIO_CREACION) VALUES
('CONSULTA GENERAL', 'CONSULTA MÉDICA GENERAL', 500.00, 'CONSULTA', 'SISTEMA'),
('CONSULTA ESPECIALIDAD', 'CONSULTA CON ESPECIALISTA', 800.00, 'CONSULTA', 'SISTEMA'),
('EXAMEN DE SANGRE', 'HEMOGRAMA COMPLETO', 300.00, 'EXAMEN', 'SISTEMA'),
('RAYOS X', 'RADIOGRAFÍA SIMPLE', 450.00, 'EXAMEN', 'SISTEMA'),
('ELECTROCARDIOGRAMA', 'ECG ESTÁNDAR', 600.00, 'EXAMEN', 'SISTEMA');

-- ============================================
-- INSERCIÓN DE USUARIO ADMINISTRADOR INICIAL - MEJORADO CON 2FA
-- ============================================

INSERT INTO TBL_MS_USUARIO (
    USUARIO, 
    NOMBRE_USUARIO, 
    ESTADO, 
    CONTRASENA, 
    ID_ROL, 
    CORREO_ELECTRONICO,
    FECHA_VENCIMIENTO,
    ACTIVO_2FA,  -- 2FA activado por defecto para admin
    USUARIO_CREACION
) VALUES (
    'ADMIN',
    'ADMINISTRADOR DEL SISTEMA',
    'ACTIVO',
    'Admin123!', -- Contraseña temporal
    (SELECT ID_ROL FROM TBL_MS_ROLES WHERE ROL = 'ADMINISTRADOR'),
    'admin@rocamaya.com',
    DATE_ADD(CURRENT_DATE, INTERVAL 30 DAY),
    1,  -- 2FA activado
    'SISTEMA'
);

-- ============================================
-- INSERCIÓN DE DATOS DE PRUEBA COMPLETOS
-- ============================================

-- Insertar pacientes con datos realistas de Honduras
INSERT INTO TBL_PACIENTE (
    NOMBRES, 
    APELLIDOS, 
    FECHA_NACIMIENTO, 
    GENERO, 
    DIRECCION, 
    TELEFONO, 
    CORREO_ELECTRONICO, 
    TIPO_DOCUMENTO_IDENTIDAD, 
    NUMERO_DOCUMENTO_IDENTIDAD, 
    RTN_PACIENTE, 
    ESTADO_CIVIL, 
    OCUPACION, 
    NOMBRE_CONTACTO_EMERGENCIA, 
    TELEFONO_CONTACTO_EMERGENCIA, 
    PARENTESCO_CONTACTO_EMERGENCIA,
    ID_USUARIO_REGISTRO,
    USUARIO_CREACION
) VALUES 
-- Paciente 1
(
    'MARÍA ELENA', 
    'GARCÍA MARTÍNEZ', 
    '1985-03-15', 
    'FEMENINO', 
    'COLONIA PALMIRA, CALLE PRINCIPAL #123, TEGUCIGALPA', 
    '+504 2234-5678', 
    'maria.garcia@email.com', 
    'DNI', 
    '0801-1985-12345', 
    '0801198501234', 
    'CASADO', 
    'CONTADORA', 
    'CARLOS GARCÍA', 
    '+504 9876-5432', 
    'ESPOSO',
    1,
    'ADMIN'
),
-- Paciente 2
(
    'JUAN CARLOS', 
    'LÓPEZ HERNÁNDEZ', 
    '1978-11-30', 
    'MASCULINO', 
    'RESIDENCIAL LOS PINOS, BLOQUE 5, CASA #45, SAN PEDRO SULA', 
    '+504 3345-6789', 
    'juan.lopez@email.com', 
    'DNI', 
    '0801-1978-98765', 
    '0801197809876', 
    'CASADO', 
    'INGENIERO INDUSTRIAL', 
    'ANA LÓPEZ', 
    '+504 8765-4321', 
    'ESPOSA',
    1,
    'ADMIN'
);

-- Insertar historiales médicos
INSERT INTO TBL_HISTORIAL_MEDICO (
    ID_PACIENTE,
    ALERGIAS,
    ENFERMEDADES_CRONICAS,
    CIRUGIAS_PREVIAS,
    MEDICAMENTOS_ACTUALES,
    ANTECEDENTES_FAMILIARES,
    HABITOS,
    VACUNAS,
    NOTAS_IMPORTANTES,
    ID_USUARIO_ACTUALIZO,
    USUARIO_CREACION
) VALUES
-- Historial para Paciente 1 (María Elena García)
(
    1,
    '["PENICILINA", "MARISCOS"]',
    '["HIPERTENSIÓN ARTERIAL"]',
    '["APENDICECTOMÍA (2010)"]',
    '["LOSARTAN 50MG", "ASPIRINA 100MG"]',
    '{"PADRE": "DIABETES", "MADRE": "HIPERTENSIÓN"}',
    '{"TABACO": "NO", "ALCOHOL": "OCASIONAL", "EJERCICIO": "3_VECES_POR_SEMANA"}',
    '["INFLUENZA_2023", "TÉTANOS_2018"]',
    'PACIENTE CON HIPERTENSIÓN CONTROLADA. REVISIONES CADA 6 MESES.',
    1,
    'ADMIN'
),
-- Historial para Paciente 2 (Juan Carlos López)
(
    2,
    '[]',
    '["DIABETES TIPO 2"]',
    '["COLECISTECTOMÍA (2015)"]',
    '["METFORMINA 850MG", "GLIBENCLAMIDA 5MG"]',
    '{"PADRE": "DIABETES", "HERMANO": "HIPERTENSIÓN"}',
    '{"TABACO": "NO", "ALCOHOL": "MODERADO", "EJERCICIO": "CAMINATAS_DIARIAS"}',
    '["INFLUENZA_2023", "COVID-19_COMPLETA"]',
    'DIABÉTICO CONTROLADO. USO DE GLUCÓMETRO DIARIO.',
    1,
    'ADMIN'
);

-- Insertar usuarios adicionales (médico, enfermera, recepcionista)
INSERT IGNORE INTO TBL_MS_USUARIO (
    USUARIO, 
    NOMBRE_USUARIO, 
    ESTADO, 
    CONTRASENA, 
    ID_ROL, 
    CORREO_ELECTRONICO,
    FECHA_VENCIMIENTO,
    ACTIVO_2FA,  -- 2FA desactivado por defecto
    USUARIO_CREACION
) VALUES 
('DR.GARCIA', 'DR. ROBERTO GARCÍA LÓPEZ', 'ACTIVO', 'Temp123!', 
 (SELECT ID_ROL FROM TBL_MS_ROLES WHERE ROL = 'DOCTOR'), 
 'dr.garcia@rocamaya.com', DATE_ADD(CURRENT_DATE, INTERVAL 30 DAY), 0, 'ADMIN'),
('ENF.ROSA', 'LIC. ROSA MARÍA HERNÁNDEZ', 'ACTIVO', 'Temp123!', 
 (SELECT ID_ROL FROM TBL_MS_ROLES WHERE ROL = 'ENFERMERA'), 
 'enf.rosa@rocamaya.com', DATE_ADD(CURRENT_DATE, INTERVAL 30 DAY), 0, 'ADMIN'),
('RECEP.ANA', 'ANA LUCÍA GÓMEZ', 'ACTIVO', 'Temp123!', 
 (SELECT ID_ROL FROM TBL_MS_ROLES WHERE ROL = 'RECEPCIONISTA'), 
 'recepcion@rocamaya.com', DATE_ADD(CURRENT_DATE, INTERVAL 30 DAY), 0, 'ADMIN');

-- Obtener IDs de usuarios
SET @id_admin = (SELECT ID_USUARIO FROM TBL_MS_USUARIO WHERE USUARIO = 'ADMIN');
SET @id_doctor = (SELECT ID_USUARIO FROM TBL_MS_USUARIO WHERE USUARIO = 'DR.GARCIA');
SET @id_enfermera = (SELECT ID_USUARIO FROM TBL_MS_USUARIO WHERE USUARIO = 'ENF.ROSA');
SET @id_recepcionista = (SELECT ID_USUARIO FROM TBL_MS_USUARIO WHERE USUARIO = 'RECEP.ANA');
SET @id_paciente = 1; -- María Elena García

-- Crear cita médica
INSERT INTO TBL_CITAS (
    ID_PACIENTE,
    ID_DOCTOR,
    FECHA_CITA,
    FECHA_FIN_ESTIMADA,
    DURACION_ESTIMADA_MIN,
    ESTADO,
    MOTIVO_CONSULTA,
    ID_USUARIOCREADOR,
    PRIORIDAD,
    TIPO_CITA,
    CANAL_REGISTRO,
    OBSERVACIONES,
    USUARIO_CREACION,
    USUARIO_MODIFICACION
) VALUES (
    @id_paciente,
    @id_doctor,
    '2024-01-15 09:00:00',
    '2024-01-15 09:30:00',
    30,
    'PROGRAMADA',
    'CONTROL DE HIPERTENSIÓN Y REVISIÓN DE MEDICACIÓN ACTUAL. PACIENTE REFIERE CEFALEA OCASIONAL.',
    @id_recepcionista,
    'NORMAL',
    'CONTROL',
    'PRESENCIAL',
    'PACIENTE PUNTUAL, TRAE EXAMENES ANTERIORES',
    'RECEP.ANA',
    'RECEP.ANA'
);

SET @id_cita = LAST_INSERT_ID();

-- Proceso de preclínica (Triaje)
INSERT INTO TBL_PRECLINICA (
    ID_CITA,
    ID_USUARIO_ENFERMERIA,
    TEMPERATURA,
    PRESION_SISTOLICA,
    PRESION_DIASTOLICA,
    FRECUENCIA_CARDIACA,
    FRECUENCIA_RESPIRATORIA,
    SATURACION_OXIGENO,
    PESO,
    TALLA,
    GLUCOSA,
    PERIMETRO_ABDOMINAL,
    OBSERVACIONES,
    ESTADO_GENERAL,
    SIGNOS_VITALES_JSON,
    USUARIO_CREACION,
    USUARIO_MODIFICACION
) VALUES (
    @id_cita,
    @id_enfermera,
    36.8,
    140,
    90,
    78,
    16,
    98.5,
    65.5,
    1.62,
    95.0,
    85.0,
    'PACIENTE EN BUEN ESTADO GENERAL. REFIERE CEFALEA LEVE. PRESIÓN ARTERIAL ELEVADA.',
    'REGULAR',
    '{"presion_arterial": "140/90", "frecuencia_cardiaca": 78, "saturacion_oxigeno": 98.5, "temperatura": 36.8}',
    'ENF.ROSA',
    'ENF.ROSA'
);

-- Actualizar estado de la cita a PRECLINICA
UPDATE TBL_CITAS SET 
    ESTADO = 'PRECLINICA',
    USUARIO_MODIFICACION = 'ENF.ROSA'
WHERE ID_CITA = @id_cita;

-- Consulta médica
UPDATE TBL_CITAS SET 
    ESTADO = 'CONSULTA_MEDICA',
    USUARIO_MODIFICACION = 'DR.GARCIA'
WHERE ID_CITA = @id_cita;

INSERT INTO TBL_CONSULTA_MEDICA (
    ID_CITA,
    ID_PACIENTE,
    ID_DOCTOR,
    MOTIVO_CONSULTA,
    SINTOMAS,
    EXAMEN_FISICO,
    DIAGNOSTICO_PRINCIPAL,
    CODIGO_CIE10_PRINCIPAL,
    DIAGNOSTICO_SECUNDARIO,
    CODIGO_CIE10_SECUNDARIO,
    TRATAMIENTO,
    RECOMENDACIONES,
    OBSERVACIONES,
    PROXIMA_CITA_RECOMENDADA,
    TIPO_CONSULTA,
    USUARIO_CREACION,
    USUARIO_MODIFICACION
) VALUES (
    @id_cita,
    @id_paciente,
    @id_doctor,
    'CONTROL DE HIPERTENSIÓN ARTERIAL',
    '["CEFALEA OCCIPITAL", "VISIÓN BORROSA OCASIONAL", "CANSANCIO"]',
    '{"cabeza_y_cuello": "NORMOCÉFALO", "cardiopulmonar": "RITMO CARDÍACO REGULAR", "abdomen": "BLANDO, NO DOLOROSO"}',
    'HIPERTENSIÓN ARTERIAL ESENCIAL NO CONTROLADA',
    'I10',
    'CEFALEA TENSIONAL',
    'G44.2',
    'AJUSTAR DOSIS DE LOSARTAN A 100MG DIARIOS. AGREGAR HIDROCLOROTIAZIDA 12.5MG. CONTROL DE PRESIÓN ARTERIAL EN CASA.',
    'DIETA BAJA EN SODIO. EJERCICIO AERÓBICO 30 MINUTOS DIARIOS. REDUCIR CONSUMO OF CAFÉ. CONTROL DE ESTRÉS.',
    'PACIENTE CON HIPERTENSIÓN NO CONTROLADA A PESAR DE TRATAMIENTO ACTUAL. SE AJUSTA MEDICACIÓN Y SE SOLICITAN EXÁMENES.',
    '2024-02-15',
    'CONTROL',
    'DR.GARCIA',
    'DR.GARCIA'
);

SET @id_consulta = LAST_INSERT_ID();

-- Verificar/insertar medicamentos en inventario
INSERT IGNORE INTO TBL_INVENTARIO_MEDICAMENTO (
    NOMBRE_MEDICAMENTO,
    NOMBRE_GENERICO,
    DESCRIPCION,
    PRESENTACION,
    CONCENTRACION,
    VIA_ADMINISTRACION,
    STOCK_ACTUAL,
    STOCK_MINIMO,
    STOCK_MAXIMO,
    PRECIO_COMPRA,
    PRECIO_VENTA,
    LOTE,
    FECHA_VENCIMIENTO,
    PROVEEDOR,
    REQUIERE_RECETA,
    ESTADO,
    FECHA_REGISTRO,
    ID_USUARIO_REGISTRO,
    USUARIO_CREACION,
    USUARIO_MODIFICACION
) VALUES 
('LOSARTAN', 'LOSARTAN POTÁSICO', 'ANTAGONISTA DE RECEPTORES DE ANGIOTENSINA II', 'TABLETAS', '100MG', 'ORAL', 
 100, 20, 200, 3.50, 5.50, 'LOT-202401-001', '2025-12-31', 'LABORATORIOS FARMACÉUTICOS S.A.', 
 TRUE, 'ACTIVO', CURRENT_TIMESTAMP, @id_admin, 'ADMIN', 'ADMIN'),
('HIDROCLOROTIAZIDA', 'HIDROCLOROTIAZIDA', 'DIURÉTICO TIAZÍDICO', 'TABLETAS', '12.5MG', 'ORAL', 
 150, 30, 300, 1.80, 3.20, 'LOT-202401-002', '2025-10-31', 'LABORATORIOS MÉDICOS HONDUREÑOS', 
 TRUE, 'ACTIVO', CURRENT_TIMESTAMP, @id_admin, 'ADMIN', 'ADMIN');

-- Obtener IDs de medicamentos
SET @id_losartan = (SELECT ID_MEDICAMENTO FROM TBL_INVENTARIO_MEDICAMENTO WHERE NOMBRE_MEDICAMENTO = 'LOSARTAN');
SET @id_hidroclo = (SELECT ID_MEDICAMENTO FROM TBL_INVENTARIO_MEDICAMENTO WHERE NOMBRE_MEDICAMENTO = 'HIDROCLOROTIAZIDA');

-- Insertar prescripciones
INSERT INTO TBL_PRESCRIPCION (
    ID_CONSULTA,
    ID_MEDICAMENTO,
    FECHA_PRESCRIPCION,
    DOSIS,
    FRECUENCIA,
    DURACION,
    CANTIDAD_TOTAL,
    INSTRUCCIONES_ADICIONALES,
    ESTADO,
    USUARIO_CREACION,
    USUARIO_MODIFICACION
) VALUES 
(@id_consulta, @id_losartan, CURRENT_TIMESTAMP, '100MG', '1 VEZ AL DÍA', '30 DÍAS', 30, 
 'TOMAR EN LA MAÑANA CON EL DESAYUNO', 'ACTIVA', 'DR.GARCIA', 'DR.GARCIA'),
(@id_consulta, @id_hidroclo, CURRENT_TIMESTAMP, '12.5MG', '1 VEZ AL DÍA', '30 DÍAS', 30, 
 'TOMAR EN LA MAÑANA', 'ACTIVA', 'DR.GARCIA', 'DR.GARCIA');

-- Generación de factura
INSERT INTO TBL_FACTURA (
    ID_CITA,
    ID_PACIENTE,
    FECHA_EMISION,
    NUMERO_FACTURA,
    ESTADO_FACTURA,
    SUBTOTAL,
    ISV,
    DESCUENTO,
    MONTO_TOTAL,
    SALDO_PENDIENTE,
    FECHA_VENCIMIENTO,
    TERMINOS_PAGO,
    USUARIO_CREACION,
    USUARIO_MODIFICACION
) VALUES (
    @id_cita,
    @id_paciente,
    CURRENT_TIMESTAMP,
    CONCAT('FACT-', DATE_FORMAT(NOW(), '%Y%m%d-'), LPAD(@id_cita, 4, '0')),
    'PENDIENTE',
    800.00,
    120.00,
    0.00,
    920.00,
    920.00,
    DATE_ADD(CURRENT_DATE, INTERVAL 15 DAY),
    'CONTADO',
    'RECEP.ANA',
    'RECEP.ANA'
);

SET @id_factura = LAST_INSERT_ID();

-- Detalles de la factura
INSERT INTO TBL_DETALLE_FACTURA (
    ID_FACTURA,
    ID_SERVICIO,
    DESCRIPCION_SERVICIO,
    CANTIDAD,
    PRECIO_UNITARIO,
    USUARIO_CREACION,
    USUARIO_MODIFICACION
) VALUES 
(@id_factura, (SELECT ID_SERVICIO FROM TBL_SERVICIOS_MEDICOS WHERE NOMBRE_SERVICIO = 'CONSULTA ESPECIALIDAD'), 
 'CONSULTA CARDIOLOGÍA - DR. GARCÍA', 1, 800.00, 'RECEP.ANA', 'RECEP.ANA');

-- Finalización de la consulta
UPDATE TBL_CITAS SET 
    ESTADO = 'FINALIZADA',
    USUARIO_MODIFICACION = 'DR.GARCIA'
WHERE ID_CITA = @id_cita;

-- Actualizar historial médico del paciente
UPDATE TBL_HISTORIAL_MEDICO SET 
    MEDICAMENTOS_ACTUALES = '["LOSARTAN 100MG", "HIDROCLOROTIAZIDA 12.5MG", "ASPIRINA 100MG"]',
    FECHA_ACTUALIZACION = CURRENT_TIMESTAMP,
    ID_USUARIO_ACTUALIZO = @id_doctor,
    USUARIO_MODIFICACION = 'DR.GARCIA'
WHERE ID_PACIENTE = @id_paciente;

-- ============================================
-- REGISTRO DE ACTIVIDADES EN BITÁCORA - MEJORADAS CON 2FA
-- ============================================

-- Registrar actividades manuales de prueba en bitácora
CALL SP_REGISTRAR_BITACORA(
    @id_admin, 
    'LOGIN_EXITOSO', 
    'Usuario ADMIN inició sesión correctamente', 
    'AUTENTICACION', 
    NULL, 
    'TBL_MS_USUARIO', 
    '192.168.1.100', 
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', 
    'EXITO', 
    NULL, 
    'SISTEMA'
);

CALL SP_REGISTRAR_BITACORA(
    @id_recepcionista, 
    'CREACION_CITA_MANUAL', 
    'Recepcionista creó cita manual para paciente María Elena García', 
    'CITAS', 
    @id_cita, 
    'TBL_CITAS', 
    '192.168.1.101', 
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', 
    'EXITO', 
    NULL, 
    'RECEP.ANA'
);

-- Registrar activación de 2FA para admin
CALL SP_REGISTRAR_BITACORA(
    @id_admin, 
    'ACTIVACION_2FA', 
    'Administrador activó autenticación de dos factores', 
    'SEGURIDAD', 
    @id_admin, 
    'TBL_MS_USUARIO', 
    '192.168.1.100', 
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', 
    'EXITO', 
    NULL, 
    'SISTEMA'
);

-- ============================================
-- VERIFICACIÓN FINAL DEL SISTEMA MEJORADO
-- ============================================

SELECT '=== VERIFICACIÓN FINAL DEL SISTEMA COMPLETO CON 2FA ===' as '';

-- Verificar todas las tablas creadas
SELECT 
    TABLE_NAME,
    TABLE_ROWS
FROM information_schema.TABLES 
WHERE TABLE_SCHEMA = 'Roca_Maya' 
ORDER BY TABLE_NAME;

-- Verificar registros en bitácora
SELECT 
    'BITÁCORA' AS MODULO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT ID_USUARIO) AS USUARIOS_REGISTRADOS,
    COUNT(DISTINCT MODULO) AS MODULOS_REGISTRADOS
FROM TBL_MS_BITACORA;

-- Mostrar resumen de actividades por módulo en bitácora
SELECT 
    MODULO,
    ESTADO_OPERACION,
    COUNT(*) AS CANTIDAD
FROM TBL_MS_BITACORA
GROUP BY MODULO, ESTADO_OPERACION
ORDER BY MODULO, ESTADO_OPERACION;

-- Mostrar estado de seguridad 2FA
SELECT 
    'SEGURIDAD 2FA' AS TIPO,
    COUNT(*) AS TOTAL_USUARIOS,
    SUM(ACTIVO_2FA) AS USUARIOS_CON_2FA,
    ROUND((SUM(ACTIVO_2FA) / COUNT(*)) * 100, 2) AS PORCENTAJE_PROTEGIDO
FROM TBL_MS_USUARIO
WHERE ESTADO = 'ACTIVO';

-- Mostrar últimos 5 registros de bitácora
SELECT 
    DATE_FORMAT(FECHA_HORA, '%Y-%m-%d %H:%i:%s') AS FECHA,
    COALESCE((SELECT USUARIO FROM TBL_MS_USUARIO WHERE ID_USUARIO = b.ID_USUARIO), 'SISTEMA') AS USUARIO,
    ACCION,
    MODULO,
    LEFT(DESCRIPCION, 50) AS DESCRIPCION,
    ESTADO_OPERACION
FROM TBL_MS_BITACORA b
ORDER BY FECHA_HORA DESC
LIMIT 5;

-- Mostrar vista de seguridad 2FA
SELECT * FROM VW_ESTADO_SEGURIDAD_2FA;
SELECT * FROM TBL_MS_BITACORA;

SELECT 'SISTEMA ROCA MAYA COMPLETO CON BITÁCORA Y 2FA IMPLEMENTADOS EXITOSAMENTE' AS ESTADO_FINAL;
USE Roca_Maya;
ALTER TABLE TBL_MS_USUARIO 
ADD COLUMN CODIGO_RECUPERACION INT NULL,
ADD COLUMN EXPIRA_CODIGO DATETIME NULL;

